// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PocketBook.Data;

#nullable disable

namespace PocketBook.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240803235024_updated Details with foreign keys to Subject again")]
    partial class updatedDetailswithforeignkeystoSubjectagain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("PocketBook.Models.AllEvent", b =>
                {
                    b.Property<int>("FacilNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FacilNo");

                    b.Property<int>("LogTypeNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LogTypeNo");

                    b.Property<string>("EventID")
                        .HasColumnType("TEXT")
                        .HasColumnName("EventID");

                    b.Property<int>("EventID_RevNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EventID_RevNo");

                    b.Property<string>("ClearanceID")
                        .HasColumnType("TEXT")
                        .HasColumnName("ClearanceID");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Details");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("EventDate");

                    b.Property<string>("EventTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("EventTime");

                    b.Property<string>("ModifyFlag")
                        .HasColumnType("TEXT")
                        .HasColumnName("ModifyFlag");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<string>("OperatorType")
                        .HasColumnType("TEXT")
                        .HasColumnName("OperatorType");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Subject");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("FacilNo", "LogTypeNo", "EventID", "EventID_RevNo");

                    b.ToTable("ESL_AllEvents");
                });

            modelBuilder.Entity("PocketBook.Models.ClearanceType", b =>
                {
                    b.Property<int>("ClearanceTypeNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClearanceTypeAbbr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClearanceTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortNo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("ClearanceTypeNo");

                    b.ToTable("ESL_ClearanceTypes");
                });

            modelBuilder.Entity("PocketBook.Models.ClearanceZone", b =>
                {
                    b.Property<string>("FacilType")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZoneNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Disable")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SortNo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("FacilType", "ZoneNo");

                    b.ToTable("ESL_ClearanceZones");
                });

            modelBuilder.Entity("PocketBook.Models.Constant", b =>
                {
                    b.Property<int>("FacilNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FacilNo");

                    b.Property<string>("ConstantName")
                        .HasColumnType("TEXT")
                        .HasColumnName("ConstantName");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("StartDate");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("EndDate");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedBy");

                    b.Property<int?>("Value")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Value");

                    b.HasKey("FacilNo", "ConstantName", "StartDate");

                    b.ToTable("ESL_Constants");
                });

            modelBuilder.Entity("PocketBook.Models.Details", b =>
                {
                    b.Property<int>("FacilNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FacilNo");

                    b.Property<int>("DetailsNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DetailsNo");

                    b.Property<string>("DetailsName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DetailsName");

                    b.Property<string>("Disable")
                        .HasColumnType("TEXT")
                        .HasColumnName("Disable");

                    b.Property<string>("FacilType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FacilType");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<int?>("SortNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SortNo");

                    b.Property<int?>("SubjectFacilNo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubjectNo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubjectRefNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SubjNo");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("FacilNo", "DetailsNo");

                    b.HasIndex("SubjectFacilNo", "SubjectNo");

                    b.ToTable("ESL_Details");
                });

            modelBuilder.Entity("PocketBook.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmployeeNo");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Company");

                    b.Property<string>("Disable")
                        .HasColumnType("TEXT")
                        .HasColumnName("Disable");

                    b.Property<int?>("FacilNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FacilNo");

                    b.Property<int?>("FacilityFacilNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FirstName");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("GroupName");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("JobTitle");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LastName");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("FacilityFacilNo");

                    b.ToTable("ESL_Employees");
                });

            modelBuilder.Entity("PocketBook.Models.EquipmentInvolved", b =>
                {
                    b.Property<int>("FacilNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FacilNo");

                    b.Property<int>("EquipNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EquipNo");

                    b.Property<string>("Disable")
                        .HasColumnType("TEXT")
                        .HasColumnName("Disable");

                    b.Property<string>("EquipName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("EquipName");

                    b.Property<string>("FacilType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("FacilNo", "EquipNo");

                    b.ToTable("ESL_EquipmentInvolved");
                });

            modelBuilder.Entity("PocketBook.Models.Facility", b =>
                {
                    b.Property<int>("FacilNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("FacilNo");

                    b.Property<string>("Disable")
                        .HasColumnType("TEXT")
                        .HasColumnName("Disable");

                    b.Property<string>("FacilAbbr")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FacilAbbr");

                    b.Property<string>("FacilFullName")
                        .HasColumnType("TEXT")
                        .HasColumnName("FacilFullName");

                    b.Property<string>("FacilName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FacilName");

                    b.Property<string>("FacilType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FacilType");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<int?>("SortNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SortNo");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("VisibleTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("VisibleTo");

                    b.HasKey("FacilNo");

                    b.ToTable("ESL_Facilities");
                });

            modelBuilder.Entity("PocketBook.Models.LogType", b =>
                {
                    b.Property<int>("LogTypeNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("LogTypeNo");

                    b.Property<string>("LogTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LogTypeName");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("LogTypeNo");

                    b.ToTable("ESL_LogTypes");
                });

            modelBuilder.Entity("PocketBook.Models.Meter", b =>
                {
                    b.Property<int>("FacilNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FacilNo");

                    b.Property<string>("MeterID")
                        .HasColumnType("TEXT")
                        .HasColumnName("MeterID");

                    b.Property<string>("Disable")
                        .HasColumnType("TEXT")
                        .HasColumnName("Disable");

                    b.Property<string>("MeterType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MeterType");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<int?>("SortNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SortNo");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("FacilNo", "MeterID");

                    b.ToTable("ESL_Meters");
                });

            modelBuilder.Entity("PocketBook.Models.PlantShift", b =>
                {
                    b.Property<int>("FacilNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShiftEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShiftName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShiftStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("FacilNo", "ShiftNo");

                    b.ToTable("PlantsShiftList");
                });

            modelBuilder.Entity("PocketBook.Models.RelatedTo", b =>
                {
                    b.Property<int>("FacilNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogTypeNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventID")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedTo_Subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("FacilNo", "LogTypeNo", "EventID", "RelatedTo_Subject");

                    b.ToTable("ESL_RelatedTo");
                });

            modelBuilder.Entity("PocketBook.Models.Subject", b =>
                {
                    b.Property<int>("FacilNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FacilNo");

                    b.Property<int>("SubjectNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SubjNo");

                    b.Property<string>("Disable")
                        .HasColumnType("TEXT")
                        .HasColumnName("Disable");

                    b.Property<string>("FacilType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FacilType");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<int?>("SortNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SortNo");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SubjName");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("FacilNo", "SubjectNo");

                    b.ToTable("ESL_Subjects");
                });

            modelBuilder.Entity("PocketBook.Models.Unit", b =>
                {
                    b.Property<int>("UnitNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("UnitNo");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<string>("UnitDesc")
                        .HasColumnType("TEXT")
                        .HasColumnName("UnitDesc");

                    b.Property<string>("UnitName")
                        .HasColumnType("TEXT")
                        .HasColumnName("UnitName");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("UnitNo");

                    b.ToTable("ESL_Units");
                });

            modelBuilder.Entity("PocketBook.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Mail");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmployeeNo");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("GivenName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Surname");

                    b.Property<string>("UserPrinicipalName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UserPrinicipalName");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ESL_Users");
                });

            modelBuilder.Entity("PocketBook.Models.WorkOrder", b =>
                {
                    b.Property<int>("FacilNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FacilNo");

                    b.Property<int>("LogTypeNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LogTypeNo");

                    b.Property<string>("EventID")
                        .HasColumnType("TEXT")
                        .HasColumnName("EventID");

                    b.Property<string>("WO_No")
                        .HasColumnType("TEXT")
                        .HasColumnName("WO_No");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("FacilNo", "LogTypeNo", "EventID", "WO_No");

                    b.ToTable("ESL_WorkOrders");
                });

            modelBuilder.Entity("PocketBook.Models.WorkToBePerformed", b =>
                {
                    b.Property<int>("WorkNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("WorkNo");

                    b.Property<string>("Disable")
                        .HasColumnType("TEXT")
                        .HasColumnName("Disable");

                    b.Property<string>("FacilType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FacilType");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<int?>("SortNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SortNo");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("WorkDescription");

                    b.HasKey("WorkNo");

                    b.ToTable("ESL_WorkToBePerformed");
                });

            modelBuilder.Entity("PocketBook.Models.Details", b =>
                {
                    b.HasOne("PocketBook.Models.Subject", null)
                        .WithMany("DetailsList")
                        .HasForeignKey("SubjectFacilNo", "SubjectNo");
                });

            modelBuilder.Entity("PocketBook.Models.Employee", b =>
                {
                    b.HasOne("PocketBook.Models.Facility", null)
                        .WithMany("EmployeeList")
                        .HasForeignKey("FacilityFacilNo");
                });

            modelBuilder.Entity("PocketBook.Models.User", b =>
                {
                    b.HasOne("PocketBook.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PocketBook.Models.Facility", b =>
                {
                    b.Navigation("EmployeeList");
                });

            modelBuilder.Entity("PocketBook.Models.Subject", b =>
                {
                    b.Navigation("DetailsList");
                });
#pragma warning restore 612, 618
        }
    }
}
